<a href="https://colab.research.google.com/github/tanu1304/DS-PROJECTS-FOR-CODSOFT/blob/main/TASK3_Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#loading the dataset
data=pd.read_csv('/content/creditcard.csv')
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
data.shape

(73377, 31)

In [ ]:
data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,73377.000000,73377.000000,73377.000000,73377.000000,73377.000000,73377.000000,73377.000000,73377.000000,73377.000000,73377.000000,...,73377.000000,73377.000000,73377.000000,73377.000000,73377.000000,73376.000000,73376.000000,73376.000000,73376.000000,73376.000000
mean,35585.573872,-0.253191,-0.026959,0.678866,0.168021,-0.272388,0.098351,-0.113787,0.055719,0.009983,...,-0.028672,-0.106260,-0.038610,0.006354,0.135416,0.024027,0.002334,0.003027,97.319552,0.002426
std,14672.723434,1.880796,1.665003,1.408884,1.372497,1.387707,1.304997,1.252286,1.234504,1.155997,...,0.737871,0.637365,0.622186,0.596241,0.439999,0.498403,0.386990,0.325267,270.209620,0.049194
min,0.000000,-56.407510,-72.715728,-33.680984,-5.172595,-42.147898,-26.160506,-31.764946,-73.216718,-9.283925,...,-34.830382,-10.933144,-26.751119,-2.836627,-7.495741,-2.534330,-9.390980,-9.617915,0.000000,0.000000
25%,29408.000000,-1.012767,-0.594981,0.191359,-0.725068,-0.890076,-0.639160,-0.604468,-0.141902,-0.676331,...,-0.225578,-0.525467,-0.178807,-0.324765,-0.128400,-0.328183,-0.063013,-0.005802,7.680000,0.000000
50%,38645.000000,-0.246674,0.071742,0.767744,0.187161,-0.304873,-0.152364,-0.073795,0.067809,-0.075887,...,-0.059954,-0.080278,-0.050791,0.062493,0.173443,-0.074571,0.009396,0.022852,26.625000,0.000000
75%,46739.000000,1.153498,0.726269,1.400254,1.052199,0.265093,0.492396,0.420147,0.347037,0.655599,...,0.116148,0.308621,0.079952,0.403607,0.422133,0.303708,0.082495,0.075879,88.970000,0.000000
max,55107.000000,1.960497,18.902453,4.226108,16.715537,34.801666,22.529298,36.677268,20.007208,10.392889,...,22.614889,10.503090,17.297845,4.014444,5.525093,3.517346,11.135740,33.847808,19656.530000,1.000000

In [ ]:
data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
73372,55105,1.104021,-1.123835,1.008939,-0.460960,-1.502758,0.021138,-1.055043,0.095135,-0.175413,...,0.405906,1.054006,-0.174455,0.155852,0.358077,-0.030114,0.048490,0.042121,119.00,0.0
73373,55105,1.182898,-0.283273,1.123494,0.066948,-1.283276,-0.900451,-0.441870,-0.150647,0.784691,...,0.082278,0.491790,-0.025468,1.078368,0.258355,1.415871,-0.060454,0.014606,22.71,0.0
73374,55106,1.168124,-0.122507,1.251822,0.860341,-1.020137,-0.277310,-0.557856,0.023732,0.802378,...,-0.077921,-0.005984,0.014309,0.452036,0.281031,0.313100,0.020995,0.030389,16.35,0.0
73375,55106,-0.339385,-2.095670,0.271543,-3.066469,0.484794,3.870704,-2.069399,0.184347,-1.615958,...,0.964115,-0.266112,-0.993763,1.033766,0.748706,-0.116168,0.153607,0.268881,322.34,0.0
73376,55107,-1.020407,0.160171,0.152264,-0.093406,-0.978017,0.074549,1.610152,0.117407,-0.948643,...,0.109380,-0.400171,0.835422,-0.428141,-0.464220,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73377 entries, 0 to 73376
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    73377 non-null  int64
 1   V1      73377 non-null  float64
 2   V2      73377 non-null  float64
 3   V3      73377 non-null  float64
 4   V4      73377 non-null  float64
 5   V5      73377 non-null  float64
 6   V6      73377 non-null  float64
 7   V7      73377 non-null  float64
 8   V8      73377 non-null  float64
 9   V9      73377 non-null  float64
 10  V10     73377 non-null  float64
 11  V11     73377 non-null  float64
 12  V12     73377 non-null  float64
 13  V13     73377 non-null  float64
 14  V14     73377 non-null  float64
 15  V15     73377 non-null  float64
 16  V16     73377 non-null  float64
 17  V17     73377 non-null  float64
 18  V18     73377 non-null  float64
 19  V19     73377 non-null  float64
 20  V20     73377 non-null  float64
 21  V21     73377 non-null  float64
 22  V22     73377 non-null  float64
 23  V23     73377 non-null  float64
 24  V24     73377 non-null  float64
 25  V25     73377 non-null  float64
 26  V26     73376 non-null  float64
 27  V27     73376 non-null  float64
 28  V28     73376 non-null  float64
 29  Amount  73376 non-null  float64
 30  Class   73376 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 17.4 MB

In [ ]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

#Handling missing values

In [ ]:
data['V26'].mean()

0.024027394944155893

In [ ]:
data['V26'].fillna(data['V26'].mean(), inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73377 entries, 0 to 73376
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    73377 non-null  int64
 1   V1      73377 non-null  float64
 2   V2      73377 non-null  float64
 3   V3      73377 non-null  float64
 4   V4      73377 non-null  float64
 5   V5      73377 non-null  float64
 6   V6      73377 non-null  float64
 7   V7      73377 non-null  float64
 8   V8      73377 non-null  float64
 9   V9      73377 non-null  float64
 10  V10     73377 non-null  float64
 11  V11     73377 non-null  float64
 12  V12     73377 non-null  float64
 13  V13     73377 non-null  float64
 14  V14     73377 non-null  float64
 15  V15     73377 non-null  float64
 16  V16     73377 non-null  float64
 17  V17     73377 non-null  float64
 18  V18     73377 non-null  float64
 19  V19     73377 non-null  float64
 20  V20     73377 non-null  float64
 21  V21     73377 non-null  float64
 22  V22     73377 non-null  float64
 23  V23     73377 non-null  float64
 24  V24     73377 non-null  float64
 25  V25     73377 non-null  float64
 26  V26     73377 non-null  float64
 27  V27     73376 non-null  float64
 28  V28     73376 non-null  float64
 29  Amount  73376 non-null  float64
 30  Class   73376 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 17.4 MB

In [ ]:
data['V27'].mean()

0.002334068963208607

In [ ]:
data['V27'].fillna(data['V27'].mean(), inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73377 entries, 0 to 73376
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    73377 non-null  int64
 1   V1      73377 non-null  float64
 2   V2      73377 non-null  float64
 3   V3      73377 non-null  float64
 4   V4      73377 non-null  float64
 5   V5      73377 non-null  float64
 6   V6      73377 non-null  float64
 7   V7      73377 non-null  float64
 8   V8      73377 non-null  float64
 9   V9      73377 non-null  float64
 10  V10     73377 non-null  float64
 11  V11     73377 non-null  float64
 12  V12     73377 non-null  float64
 13  V13     73377 non-null  float64
 14  V14     73377 non-null  float64
 15  V15     73377 non-null  float64
 16  V16     73377 non-null  float64
 17  V17     73377 non-null  float64
 18  V18     73377 non-null  float64
 19  V19     73377 non-null  float64
 20  V20     73377 non-null  float64
 21  V21     73377 non-null  float64
 22  V22     73377 non-null  float64
 23  V23     73377 non-null  float64
 24  V24     73377 non-null  float64
 25  V25     73377 non-null  float64
 26  V26     73377 non-null  float64
 27  V27     73377 non-null  float64
 28  V28     73376 non-null  float64
 29  Amount  73376 non-null  float64
 30  Class   73376 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 17.4 MB

In [ ]:
data['V28'].mean()
data['V28'].fillna(data['V28'].mean(), inplace=True)

In [ ]:
data['Amount'].mean()
data['Amount'].fillna(data['Amount'].mean(), inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73377 entries, 0 to 73376
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    73377 non-null  int64
 1   V1      73377 non-null  float64
 2   V2      73377 non-null  float64
 3   V3      73377 non-null  float64
 4   V4      73377 non-null  float64
 5   V5      73377 non-null  float64
 6   V6      73377 non-null  float64
 7   V7      73377 non-null  float64
 8   V8      73377 non-null  float64
 9   V9      73377 non-null  float64
 10  V10     73377 non-null  float64
 11  V11     73377 non-null  float64
 12  V12     73377 non-null  float64
 13  V13     73377 non-null  float64
 14  V14     73377 non-null  float64
 15  V15     73377 non-null  float64
 16  V16     73377 non-null  float64
 17  V17     73377 non-null  float64
 18  V18     73377 non-null  float64
 19  V19     73377 non-null  float64
 20  V20     73377 non-null  float64
 21  V21     73377 non-null  float64
 22  V22     73377 non-null  float64
 23  V23     73377 non-null  float64
 24  V24     73377 non-null  float64
 25  V25     73377 non-null  float64
 26  V26     73377 non-null  float64
 27  V27     73377 non-null  float64
 28  V28     73377 non-null  float64
 29  Amount  73377 non-null  float64
 30  Class   73377 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 17.4 MB

In [ ]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
#distribution of legir transactions & fraudulent transaction
data['Class'].value_counts()

Class
0.000000    73198
1.000000      178
0.002426        1
Name: count, dtype: int64

this dataset is highly unbalanced
  

* 0->Normal Transcation
*     1->fraudulent transaction

In [ ]:
#separating the data for analysis
legit=data[data.Class==0]
fraud=data[data.Class==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(73198, 31)
(178, 31)

In [ ]:
#Statistical measures of the data
legit.Amount.describe()

count    73198.000000
mean        97.324727
std        270.324183
min          0.000000
25%          7.680000
50%         26.675000
75%         88.947500
max      19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     178.000000
mean       95.191461
std       218.660540
min         0.000000
25%         1.000000
50%         7.595000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
#Compare the values for both transactions
data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.000000,35597.170893,-0.237300,-0.038920,0.702672,0.155577,-0.260766,0.103663,-0.096812,0.047751,0.017704,...,0.044057,-0.030721,-0.106049,-0.038141,0.006549,0.135145,0.023827,0.000959,0.002925,97.324727
0.002426,55107.000000,-1.020407,0.160171,0.152264,-0.093406,-0.978017,0.074549,1.610152,0.117407,-0.948643,...,0.844151,0.109380,-0.400171,0.835422,-0.428141,-0.464220,0.024027,0.002334,0.003027,97.319552
1.000000,30706.921348,-6.783789,4.890766,-9.107666,5.286608,-5.047343,-2.085865,-7.104280,3.332048,-3.159344,...,0.420153,0.813143,-0.191093,-0.236559,-0.071391,0.249935,0.106447,0.567944,0.044848,95.191461

#Under-Sampling

Build a Sample dataset containing similar distribution of normal transactions and fraudulent transactions

Number of fradulent transaction-?>178

In [ ]:
legit_sample=legit.sample(n=178)

Concatenating two dataframes

In [ ]:
new_dataset=pd.concat([legit_sample,fraud],axis=0)
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
64164,51057,-2.426498,1.245393,0.456538,0.063953,-0.307070,-0.690752,-0.106668,0.704381,-0.287515,...,-0.214500,-0.412064,0.554184,0.070064,-0.058933,0.086097,-0.300723,0.122101,9.85,0.0
33493,37255,1.086227,-0.250572,-1.527851,0.275611,2.251396,3.438627,-0.123033,0.736383,-0.088167,...,-0.022998,-0.302619,-0.277836,1.024586,0.958461,-0.257033,-0.009039,0.025826,111.74,0.0
50988,44738,-2.167806,-0.930759,1.954131,0.367399,1.601962,1.546684,0.151179,0.315940,0.897991,...,-0.684143,-0.732545,0.657690,-1.727908,0.892809,-0.489644,0.013336,-0.408264,13.24,0.0
17791,28918,1.282460,0.076251,-1.182846,0.066794,2.192267,3.384442,-0.444456,0.798569,-0.147359,...,0.019303,-0.052939,-0.148124,1.007767,0.832191,-0.265805,0.019972,0.015916,7.90,0.0
8843,12094,1.120380,-0.248450,0.737945,0.525663,-0.933417,-0.887130,-0.205883,-0.246435,2.049248,...,-0.207311,-0.248830,-0.061171,0.752626,0.350594,1.046742,-0.105529,0.007477,68.60,0.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    178
1.0    178
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,36382.539326,-0.402955,-0.156462,0.518014,0.080368,-0.216713,0.292723,0.126404,-0.075349,0.039506,...,-0.027862,-0.019083,-0.216547,-0.087963,0.014676,0.193843,-0.030988,-0.070531,-0.028156,125.048146
1.0,30706.921348,-6.783789,4.890766,-9.107666,5.286608,-5.047343,-2.085865,-7.104280,3.332048,-3.159344,...,0.420153,0.813143,-0.191093,-0.236559,-0.071391,0.249935,0.106447,0.567944,0.044848,95.191461

Splitting the data into features and target

In [ ]:
X=new_dataset.drop(columns='Class',axis=1)
Y=new_dataset['Class']
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
64164  51057 -2.426498  1.245393  0.456538  0.063953 -0.307070 -0.690752
33493  37255  1.086227 -0.250572 -1.527851  0.275611  2.251396  3.438627
50988  44738 -2.167806 -0.930759  1.954131  0.367399  1.601962  1.546684
17791  28918  1.282460  0.076251 -1.182846  0.066794  2.192267  3.384442
8843   12094  1.120380 -0.248450  0.737945  0.525663 -0.933417 -0.887130
...      ...       ...       ...       ...       ...       ...       ...
69498  53451  0.385108  1.217620 -1.953872  2.087076 -1.144225 -0.576888
69980  53658 -1.739341  1.344521 -0.534379  3.195291 -0.416196 -1.261961
70141  53727 -1.649279  1.263974 -1.050826  2.237991 -2.527889 -0.889940
70589  53937 -2.042608  1.573578 -2.372652 -0.572676 -2.097353 -0.174142
72757  54846 -2.986466 -0.000891  0.605887  0.338338  0.685448 -1.581954

             V7        V8        V9  ...       V20       V21       V22  \
64164 -0.106668  0.704381 -0.287515  ... -0.422296 -0.214500 -0.412064
33493 -0.123033  0.736383 -0.088167  ...  0.176125 -0.022998 -0.302619
50988  0.151179  0.315940  0.897991  ... -0.720065 -0.684143 -0.732545
17791 -0.444456  0.798569 -0.147359  ... -0.009665  0.019303 -0.052939
8843  -0.205883 -0.246435  2.049248  ... -0.020783 -0.207311 -0.248830
...         ...       ...       ...  ...       ...       ...       ...
69498 -2.582865  0.643230 -1.191233  ...  0.380545  0.594623  0.372144
69980 -2.340991  0.713004 -1.416265  ...  0.002749  0.383180 -0.213952
70141 -2.355254  0.854659 -1.281243  ...  0.087406  0.679176  0.731907
70589 -3.039520 -1.634233 -0.594809  ...  0.825566 -0.723326  0.501222
72757  0.504206 -0.233403  0.636768  ... -0.764274 -0.875146 -0.509849

            V23       V24       V25       V26       V27       V28  Amount
64164  0.554184  0.070064 -0.058933  0.086097 -0.300723  0.122101    9.85
33493 -0.277836  1.024586  0.958461 -0.257033 -0.009039  0.025826  111.74
50988  0.657690 -1.727908  0.892809 -0.489644  0.013336 -0.408264   13.24
17791 -0.148124  1.007767  0.832191 -0.265805  0.019972  0.015916    7.90
8843  -0.061171  0.752626  0.350594  1.046742 -0.105529  0.007477   68.60
...         ...       ...       ...       ...       ...       ...     ...
69498 -0.310456 -0.624065  0.840216 -0.159452  0.599482  0.288916    8.00
69980 -0.336640  0.237076  0.246003 -0.044228  0.510729  0.220952    0.00
70141  0.333045  0.392505 -0.274197  0.802349  0.390809  0.112146  112.45
70589 -0.696892 -0.600514  0.127547 -0.786072  0.606097  0.171697  261.87
72757  1.313918  0.355065  0.448552  0.193490  1.214588 -0.013923    1.79

[356 rows x 30 columns]

In [ ]:
print(Y)

64164    0.0
33493    0.0
50988    0.0
17791    0.0
8843     0.0
        ...
69498    1.0
69980    1.0
70141    1.0
70589    1.0
72757    1.0
Name: Class, Length: 356, dtype: float64

Splitting the data into training and testing

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)
print(Y.shape,Y_train.shape)

(356, 30) (284, 30) (72, 30)
(356,) (284,)

#Model Training

In [ ]:
model=LogisticRegression()

In [ ]:
#Training the Logistic  Regression Model
model.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

In [ ]:
#accuracy on training data
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)
print('Accuracy on Training data:',training_data_accuracy)

Accuracy on Training data: 0.9401408450704225

In [ ]:
#accuracy on testing data
X_test_prediction=model.predict(X_test)
testing_data_accuracy=accuracy_score(X_test_prediction,Y_test)
print('Accuracy on Testing data:',testing_data_accuracy)

Accuracy on Testing data: 0.9166666666666666